language: ruby
branches:
  only:
    - master
rvm:
  - 2.3.3
  - 2.3.4
  - 2.4.1
services:
  - postgresql
env:
  - DB_USERNAME=postgres
before_install:
  - curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
  - sudo apt-get install -y nodejs
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 0.27.5
  - export PATH=$HOME/.yarn/bin:$PATH
before_script: bundle exec rake db:create
script: bundle exec rspec spec
cache:
  bundler: true
  yarn: true
