language: ruby
branches:
  only:
    - master
rvm: 2.4.1
services:
  - postgresql

addons:
  chrome: stable

env:
  - DB_USERNAME=postgres

before_install:
  - nvm install 6
  - nvm use 6
  - node -v
  - npm install -g yarn
  - if [ ! -f $PWD/chromedriver/chromedriver ]; then
      wget http://chromedriver.storage.googleapis.com/2.38/chromedriver_linux64.zip -O $PWD/chromedriver/chromedriver_linux64.zip;
      unzip $PWD/chromedriver/chromedriver_linux64.zip -d $PWD/chromedriver;
    fi

before_script: bundle exec rake db:create yarn:install
script: PATH=$PWD/chromedriver:$PATH bundle exec rspec spec

cache:
  bundler: true
  directories:
  - node_modules
  - $PWD/chromedriver
  yarn: true
